// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Report_Card_System.Models;

#nullable disable

namespace Report_Card_System.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250625134409_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Report_Card_System.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicYear = "2024-2025",
                            Name = "10th Grade",
                            Section = "A"
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mid Term"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Final Exam"
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.ExamSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ExamSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamId = 1,
                            MaxMarks = 50,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExamId = 1,
                            MaxMarks = 50,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExamId = 2,
                            MaxMarks = 100,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExamId = 2,
                            MaxMarks = 100,
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("MarksObtained")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamSubjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamSubjectId = 1,
                            MarksObtained = 45,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExamSubjectId = 2,
                            MarksObtained = 40,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExamSubjectId = 1,
                            MarksObtained = 48,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            ExamSubjectId = 2,
                            MarksObtained = 42,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExamSubjectId = 3,
                            MarksObtained = 88,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExamSubjectId = 4,
                            MarksObtained = 90,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExamSubjectId = 3,
                            MarksObtained = 92,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 8,
                            ExamSubjectId = 4,
                            MarksObtained = 91,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("Report_Card_System.Models.ExamSubject", b =>
                {
                    b.HasOne("Report_Card_System.Models.Exam", "Exam")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report_Card_System.Models.Subject", "Subject")
                        .WithMany("ExamSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Report_Card_System.Models.Mark", b =>
                {
                    b.HasOne("Report_Card_System.Models.ExamSubject", "ExamSubject")
                        .WithMany("Marks")
                        .HasForeignKey("ExamSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report_Card_System.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Report_Card_System.Models.Student", b =>
                {
                    b.HasOne("Report_Card_System.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Report_Card_System.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Report_Card_System.Models.Exam", b =>
                {
                    b.Navigation("ExamSubjects");
                });

            modelBuilder.Entity("Report_Card_System.Models.ExamSubject", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Report_Card_System.Models.Subject", b =>
                {
                    b.Navigation("ExamSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
